name: tindahan_ko_flutter
description: Tindahan Ko - Para sa mga Reyna ng Tahanan
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Styling
  google_fonts: ^6.1.0
  
  # Barcode Scanning (temporarily disabled for build)
  # mobile_scanner: ^7.1.2
  # permission_handler: ^12.0.1
  
  # Database & Storage
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # State Management
  provider: ^6.1.1
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.1.0
  # vibration: ^1.8.4  # temporarily disabled
  
  # File Operations (temporarily disabled for build)
  # share_plus: ^12.0.0
  # file_picker: ^8.1.2
  
  # Notifications (temporarily disabled for build)
  # flutter_local_notifications: ^19.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true